# Generated by Django 2.1.15 on 2020-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200722_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='vwatermeter',
            name='descriptions',
            field=models.CharField(blank=True, db_column='descriptions', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
