# Generated by Django 2.1.15 on 2020-07-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200724_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image1',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
    ]
