# Generated by Django 2.1.15 on 2020-07-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_station_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image2',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
        migrations.AddField(
            model_name='station',
            name='image3',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
        migrations.AddField(
            model_name='station',
            name='image4',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
        migrations.AddField(
            model_name='station',
            name='image5',
            field=models.ImageField(blank=True, upload_to='stations'),
        ),
    ]
