# Generated by Django 2.1.15 on 2020-09-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FenceDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('ftype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('createDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='创建人')),
                ('updateDataUsername', models.CharField(blank=True, max_length=30, null=True, verbose_name='修改人')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('cid', models.CharField(blank=True, max_length=100, null=True)),
                ('pId', models.CharField(blank=True, max_length=100, null=True)),
                ('dma_no', models.CharField(blank=True, max_length=30, null=True)),
                ('updateDataTime', models.DateTimeField(auto_now=True)),
                ('createDataTime', models.DateTimeField(auto_now_add=True)),
                ('belongto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'db_table': 'bsc_fencedistrict',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FenceShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zonetype', models.CharField(blank=True, max_length=30, null=True, verbose_name='区域类型')),
                ('shape', models.CharField(blank=True, max_length=30, null=True, verbose_name='形状')),
                ('geomdata', models.TextField(blank=True, null=True)),
                ('geomjson', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=30, null=True)),
                ('administrativeLngLat', models.TextField()),
                ('strokeColor', models.CharField(blank=True, max_length=100, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'bsc_fenceshape',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fencedistrict',
            name='shape',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ggis.FenceShape'),
        ),
    ]
