# Generated by Django 2.0 on 2020-07-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HdbWatermeterData',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('wateraddr', models.CharField(blank=True, db_column='WaterAddr', max_length=30, null=True)),
                ('readtime', models.CharField(blank=True, db_column='ReadTime', max_length=30, null=True)),
                ('meterstate', models.CharField(blank=True, db_column='MeterState', max_length=30, null=True)),
                ('flux', models.CharField(blank=True, db_column='Flux', max_length=64, null=True)),
                ('plustotalflux', models.CharField(blank=True, db_column='PlusTotalFlux', max_length=64, null=True)),
                ('reversetotalflux', models.CharField(blank=True, db_column='ReverseTotalFlux', max_length=64, null=True)),
                ('totalflux', models.CharField(blank=True, db_column='TotalFlux', max_length=64, null=True)),
                ('gprsv', models.CharField(blank=True, db_column='GprsV', max_length=64, null=True)),
                ('meterv', models.CharField(blank=True, db_column='MeterV', max_length=64, null=True)),
            ],
            options={
                'db_table': 'hdb_watermeter_data',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='bigmeter',
            options={'managed': False, 'ordering': ['-fluxreadtime']},
        ),
    ]
