# Generated by Django 2.1.15 on 2020-09-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amrs', '0002_auto_20200722_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='alarmprocess',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='amrsparam',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bigmeter',
            options={'managed': True, 'ordering': ['-fluxreadtime']},
        ),
        migrations.AlterModelOptions(
            name='bindbigmeter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindcommunity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindgrouprole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindmenugrouprole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindmenuuserrole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindusergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='binduserrole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='changewatermeter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='community',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='concentrator',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='firehydrant',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbcommunityrdc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbflowdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbflowdataday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbflowdatahour',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbflowdatamonth',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbpressuredata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbsimflow',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbwatermeterdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbwatermeterday',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdbwatermetermonth',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='imexport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='metercomm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meterparameter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='meterprotocol',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipemapnode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipemapnodetype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipepressure',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seconddistrict',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='secondwater',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stnalarmbind',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='syncscada',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usergrouprole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usermenu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='watermeter',
            options={'managed': True},
        ),
    ]
